### ISSUE TITLE
Blank attachment automatically added when adding a tag

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#183]
Reproduce: 
- Go to the DB, in the template table
- Look at the attachments. Some have "[NULL]" as value, those are the problematic ones. 

--> When you save the template with the new tag, it adds a blank attachment to the template. Then, you can't insert the template anymore, which is the main issue. 

![image](https://cloud.githubusercontent.com/assets/5151742/15017076/673f8976-1214-11e6-90c0-246afea22353.png)

<img width="330" alt="db0_ _gorgias_ _quicktext" src="https://cloud.githubusercontent.com/assets/5151742/15320733/685d00fe-1c32-11e6-8d59-bc305b8e05a0.png">

**Comment by RomainLapeyre** [comment]
2 customers have this issue, we need to fix it.

**Comment by ticruz38** [comment]
As I told you, I have no idea why adding tags on multiple template end up by adding an empty file link. However a quick fix would be to check in the file list for empty link and remove them automatically. If you want me to introduce that bug fix I can do that.

**Comment by RomainLapeyre** [comment]
Thanks for responding this fast @ticruz38. It's not a tag pb, it's when a template is saved (with or without tags), sometimes it adds "[null]" as the attachment value in the DB instead of "null". Does that help?

**Comment by ticruz38** [comment]
Yes it does, should be an easy fix

Le mer. 18 mai 2016 10:25, RomainLapeyre <notifications@github.com> a
écrit :

**Comment by ticruz38** [comment]
Well: 
for newest templates we submit default values with empty array for attachments,
for updated templates we require values and submit those values for building our template.
Both object are submitted to angular.copy for some reason. The bug may come form that function returning either an empty array or an array filling with one null value.

my fix would be to submit default values with null value on attachment property instead of an empty array when there is no attachments in the template. So we do not get that [null] array anymore.

**Comment by RomainLapeyre** [comment]
Sounds pretty easy, cool.

**Comment by ticruz38** [comment]
checkout the pull request => https://github.com/gorgias/gorgias-chrome/pull/188
try to reproduce the bug on my branch... shouldnt be there anymore!
