### ISSUE TITLE
Unable to use into OTRS system

### ISSUE THREAD

**Issue by yoanc** [gorgias/gorgias-chrome#250]
Hello,
Can anyone help me to implement this great tool for OTRS please?
It will reduce a lot my work.
Thank you

**Comment by xarg** [comment]
Hi @yoanc! Thanks for the suggestion, but we only add support for very popular tools. The reason we do this is because it's hard for us to support all the different websites specifically, we just don't have the resources. If OTRS gets a lot of requests, then we'll implement it, otherwise I suggest you fork this project and add the functionality yourself.
