### ISSUE TITLE
Reload the page after login

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#261]
## Problem
Customers tell us "I can't login with my password"

## Steps to reproduce
- Go to the settings in the extension (chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/pages/options.html#/settings)
- Click on login
- After you enter your creds and click on login:
![image](https://user-images.githubusercontent.com/5151742/32918786-5d6bb2e8-cad8-11e7-9e5e-fb0af85c2818.png)
- You're not immediately logged in:
![image](https://user-images.githubusercontent.com/5151742/32918817-7c1e4e9e-cad8-11e7-8c18-8a047fd01b0b.png)

--> You need to refresh the page, and then you're logged in.

**Comment by RomainLapeyre** [comment]
@xarg can you assign this to someone as this is causing 1-2 support tickets per week?

**Comment by ghinda** [comment]
I can take a look on Monday. Is that ok?

**Comment by xarg** [comment]
Sure, sounds good.

**Comment by ghinda** [comment]
I couldn't reproduce the issue, but have implemented page reload after login either way. Seems better than having to rely on `$broadcast`.

I tested the version on `master` and the one on the chrome store.

@RomainLapeyre can you check the console to see if there are any errors? Just in case the problem was somewhere else.
